
---

## Ansible user
# change this if running Ansible as a non-root user
# would require sudo, e.g. AWS EC2 uses ec-user
ansible_system_user: root

### Firewall management ###
# Set to true to deploy firewall rules for nagios server
manage_firewall: true
# Set to true to deploy firewall rules for client nrpe
manage_firewall_client: true

### Nagios Variables ###
nagios_plugin_path: /usr/lib64/nagios/plugins
nagios_username: nagiosadmin
nagios_password: nagiosadmin
nagios_create_guest_user: true
nagios_ro_username: guest
nagios_ro_password: guest
nagios_http_port: 80
nagios_https_port: 443
admin_name_01: nagiosadmin
# change this to your email address if you want notifications
admin_email_01: nagios@localhost
# set to false if you don't want to monitor swap
# on your nagios server
nagios_host_monitor_swap: true

### NRPE variables ###
nrpe_tcp_port: 5666

# threshold for # of processes
warning_proc: 900
critical_proc: 1000
# threshold for # of logged in users
warning_users: 15
critical_users: 30


### snmp options ###
# these are for dell idrac only
snmp_mib_path: /usr/share/snmp/mibs
snmp_opts: -v2c -c public
# these flag for strings to match failure, warn or ok
snmp_check_thresholds: --warn '$ALL$' --crit 'critical|nonRecoverable|fail' --ok 'ok|online|on|spunup|full|ready|enabled|unknown|presence'
